let products=[];let state={category:'All',collection:'All',type:'All',query:'',max:3000,sort:'popular',cart:JSON.parse(localStorage.getItem('stylenest-cart')||'[]'),wish:JSON.parse(localStorage.getItem('stylenest-wish')||'[]'),token:localStorage.getItem('stylenest-token')||''};
const $=s=>document.querySelector(s);const money=n=>'₹'+Number(n).toLocaleString('en-IN');const save=()=>{localStorage.setItem('stylenest-cart',JSON.stringify(state.cart));localStorage.setItem('stylenest-wish',JSON.stringify(state.wish));renderCart()};
async function init(){try{const r=await fetch('/api/products');const remote=await r.json();products=Array.isArray(remote)&&remote.length?remote:(window.seedProducts||[])}catch(e){products=window.seedProducts||[]}renderCart();render();if(state.token)checkMe()}
function setCategory(c,t='All'){state.category=c;state.collection='All';state.type=t;$('#categoryFilter').value=c;$('#collectionFilter').value='All';$('#typeFilter').value=t;render()}
function setCollection(c){state.collection=c;state.category='All';state.type='All';$('#categoryFilter').value='All';$('#collectionFilter').value=c;$('#typeFilter').value='All';render()}
function filtered(){let q=state.query.toLowerCase();let a=products.filter(p=>(state.category==='All'||p.category===state.category)&&(state.collection==='All'||p.collection===state.collection)&&(state.type==='All'||p.type===state.type)&&p.price<=state.max&&(!q||`${p.name} ${p.category} ${p.type} ${p.color}`.toLowerCase().includes(q)));if(state.sort==='low')a.sort((x,y)=>x.price-y.price);if(state.sort==='high')a.sort((x,y)=>y.price-x.price);if(state.sort==='new')a.sort((x,y)=>y.id-x.id);return a}
function render(){const a=filtered();$('#resultCount').textContent=`${a.length} products`;$('#catalogTitle').textContent=state.query?`Results for “${state.query}”`:state.collection!=='All'?state.collection:state.category==='All'?'Trending for you':`${state.category} Collection`;$('#productGrid').innerHTML=a.map(p=>`<article class="card"><div class="pic" onclick="viewProduct(${p.id})"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="badge">50% OFF</span><button class="heart" onclick="event.stopPropagation();toggleWish(${p.id})">${state.wish.includes(p.id)?'♥':'♡'}</button></div><div class="info"><h3>${p.name}</h3><div class="rating">★ ${p.rating} (${p.reviews})</div><div class="price">${money(p.price)} <span class="old">${money(p.oldPrice)}</span></div><button class="add" onclick="addToCart(${p.id})">Add to Cart</button></div></article>`).join('')}
function viewProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$('#modalContent').innerHTML=`<div class="product-detail"><img src="${p.image}" alt="${p.name}"><div><p class="muted">${p.category} • ${p.type}</p><h2>${p.name}</h2><div class="rating">★ ${p.rating} (${p.reviews} reviews)</div><div class="price">${money(p.price)} <span class="old">${money(p.oldPrice)}</span></div><p>${p.color} • Available sizes: ${p.size}</p><button class="primary" onclick="addToCart(${p.id});closeModal();openDrawer()">Add to Cart</button><button class="primary" style="margin-left:8px" onclick="buyNow(${p.id})">Buy Now</button></div></div>`;$('#modal').classList.add('open')}
function buyNow(id){addToCart(id);closeModal();openCheckout()}
function addToCart(id){const i=state.cart.find(x=>x.id===id);if(i)i.qty++;else state.cart.push({id,qty:1});save();openDrawer()}
function renderCart(){let count=state.cart.reduce((s,x)=>s+x.qty,0);$('#cartCount').textContent=count;let total=0;$('#cartItems').innerHTML=state.cart.length?state.cart.map(x=>{let p=products.find(y=>y.id===x.id);if(!p)return '';total+=p.price*x.qty;return `<div class="cart-row"><img src="${p.image}"><div style="flex:1"><h4>${p.name}</h4><div>${money(p.price)} × ${x.qty}</div><button onclick="removeCart(${p.id})">Remove</button></div></div>`}).join(''):'<p>Your cart is empty.</p>';$('#cartTotal').textContent=money(total)}
function removeCart(id){state.cart=state.cart.filter(x=>x.id!==id);save()}function openDrawer(){renderCart();$('#drawer').classList.add('open')}function closeDrawer(){$('#drawer').classList.remove('open')}function closeModal(){$('#modal').classList.remove('open')}function closeCheckout(){$('#checkout').classList.remove('open')}
function openCheckout(){if(!state.token){openAccount();return}if(!state.cart.length){alert('Add a product first.');return}closeDrawer();let total=state.cart.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.qty,0);$('#checkoutContent').innerHTML=`<h2>Secure UPI Payment</h2><p>Total payable: <b>${money(total)}</b></p><img class="qr" src="phonepe-qr.jpeg" alt="PhonePe QR Code"><div class="payment-note"><b>UPI / PhonePe only</b><br>Scan and pay. COD is OFF. Automatic payment confirmation requires a merchant payment gateway; until then orders remain pending verification.</div><form class="checkout-form" onsubmit="placeOrder(event)"><input required name="name" value="${state.user?.name||''}" placeholder="Full name"><input required name="phone" pattern="[0-9]{10}" placeholder="10-digit mobile number"><textarea required name="address" rows="3" placeholder="Complete delivery address"></textarea><input required name="city" placeholder="City"><input required name="pincode" pattern="[0-9]{6}" placeholder="6-digit PIN code"><button class="primary" type="submit">I Have Paid — Place Order</button></form>`;$('#checkout').classList.add('open')}
async function placeOrder(e){e.preventDefault();const f=e.target;const customer={name:f.name.value.trim(),phone:f.phone.value.trim(),address:f.address.value.trim(),city:f.city.value.trim(),pincode:f.pincode.value.trim()};const items=state.cart.map(x=>({id:x.id,qty:x.qty}));const total=state.cart.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.qty,0);try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+state.token},body:JSON.stringify({customer,items,total,paymentMethod:'UPI'})});const d=await r.json();if(!r.ok)throw Error(d.error);state.cart=[];save();$('#checkoutContent').innerHTML=`<div class="order-success"><h2>✓ Order Submitted</h2><p>Order ID: <b>${d.id}</b></p><p>Payment: <b>${d.paymentStatus}</b></p><button class="primary" onclick="closeCheckout();trackOrder('${d.id}')">Track Order</button></div>`}catch(err){alert(err.message)}}
function toggleWish(id){state.wish=state.wish.includes(id)?state.wish.filter(x=>x!==id):[...state.wish,id];save();render()}
function clearFilters(){state={...state,category:'All',type:'All',max:3000,sort:'popular',query:''};$('#categoryFilter').value='All';$('#typeFilter').value='All';$('#priceFilter').value=3000;$('#sortFilter').value='popular';$('#searchInput').value='';$('#priceValue').textContent=3000;render()}
function openAccount(){if(state.token){$('#modalContent').innerHTML=`<h2>My Account</h2><p>Logged in as <b>${state.user?.name||'Customer'}</b></p><p>${state.user?.email||''}</p><button class="primary" onclick="myOrders()">My Orders</button> <button class="primary" onclick="logout()">Logout</button>`;$('#modal').classList.add('open');return}$('#modalContent').innerHTML=`<h2>Customer Account</h2><div class="auth-tabs"><button onclick="authForm('login')">Login</button><button onclick="authForm('register')">Create account</button></div><div id="authForm"></div>`;$('#modal').classList.add('open');authForm('login')}
function authForm(mode){$('#authForm').innerHTML=`<form class="checkout-form" onsubmit="submitAuth(event,'${mode}')">${mode==='register'?'<input required name="name" placeholder="Full name">':''}<input required name="email" type="email" placeholder="Email"><input required name="password" type="password" minlength="6" placeholder="Password"><button class="primary">${mode==='login'?'Login':'Create account'}</button></form>`}
async function submitAuth(e,mode){e.preventDefault();const o=Object.fromEntries(new FormData(e.target));try{const r=await fetch('/api/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(o)});const d=await r.json();if(!r.ok)throw Error(d.error);state.token=d.token;state.user=d.user;localStorage.setItem('stylenest-token',d.token);closeModal();if(mode==='register')alert('Account created successfully')}catch(err){alert(err.message)}}
async function checkMe(){try{const r=await fetch('/api/auth/me',{headers:{Authorization:'Bearer '+state.token}});if(!r.ok)throw 0;state.user=await r.json()}catch(e){state.token='';localStorage.removeItem('stylenest-token')}}
async function logout(){await fetch('/api/auth/logout',{method:'POST',headers:{Authorization:'Bearer '+state.token}}).catch(()=>{});state.token='';state.user=null;localStorage.removeItem('stylenest-token');closeModal()}
async function myOrders(){try{const r=await fetch('/api/orders',{headers:{Authorization:'Bearer '+state.token}});const a=await r.json();$('#modalContent').innerHTML='<h2>My Orders</h2>'+(a.length?a.map(o=>`<div class="order-box"><b>${o.id}</b><span>${money(o.total)}</span><p>${o.status} • ${o.paymentStatus}</p><button class="primary" onclick="trackOrder('${o.id}')">Track</button></div>`).join(''):'<p>No orders yet.</p>')}catch(e){alert('Could not load orders')}}
async function trackOrder(id){try{const r=await fetch('/api/orders/'+id,{headers:{Authorization:'Bearer '+state.token}});const o=await r.json();if(!r.ok)throw Error(o.error);$('#modalContent').innerHTML=`<h2>Order ${o.id}</h2><p><b>${o.status}</b></p><p>Payment: ${o.paymentStatus}</p><div class="steps"><span class="done">Placed</span><span class="${['Processing','Shipped','Out for delivery','Delivered'].includes(o.status)?'done':''}">Processing</span><span class="${['Shipped','Out for delivery','Delivered'].includes(o.status)?'done':''}">Shipped</span><span class="${['Out for delivery','Delivered'].includes(o.status)?'done':''}">Out for delivery</span><span class="${o.status==='Delivered'?'done':''}">Delivered</span></div>`;$('#modal').classList.add('open')}catch(e){alert(e.message)}}
$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;render()});$('#searchBtn').onclick=()=>{state.query=$('#searchInput').value;render()};$('#cartBtn').onclick=openDrawer;$('#accountBtn').onclick=openAccount;$('#wishlistBtn').onclick=()=>{state.query='';state.category='All';render();alert('Your wishlist has '+state.wish.length+' saved item(s).')};$('#categoryFilter').onchange=e=>{state.category=e.target.value;render()};$('#typeFilter').onchange=e=>{state.type=e.target.value;render()};$('#sortFilter').onchange=e=>{state.sort=e.target.value;render()};$('#priceFilter').oninput=e=>{state.max=+e.target.value;$('#priceValue').textContent=e.target.value;render()};$('#collectionFilter').addEventListener('change',e=>setCollection(e.target.value));
init();
